name: Status Checks

on:
  push:

jobs:
  ql_check_missing:
    runs-on: ubuntu-latest
    name: make ql-check (missing)
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install SBCL
        run: |
          sudo apt-get update
          sudo apt-get install -y sbcl

      - name: make ql-check
        run: make ql-check
  ql_install:
    runs-on: ubuntu-latest
    name: make ql-install
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install SBCL
        run: |
          sudo apt-get update
          sudo apt-get install -y sbcl

      - name: make ql-install-ci
        run: make ql-install-ci

      - name: make ql-check-ci
        run: make ql-check-ci
   build:
    runs-on: ubuntu-latest
    name: make build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install SBCL
        run: |
          sudo apt-get update
          sudo apt-get install -y sbcl

      - name: make ql-install-ci
        run: make ql-install-ci

      - name: make ql-check-ci
        run: make ql-check-ci

      - name: make build
        run: make build